update=Sat 31 Aug 2013 04:26:44 PM EEST
version=1
last_client=pcbnew
[general]
version=1
[eeschema]
version=1
LibDir=
NetFmtName=PcbnewAdvanced
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=special
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=/home/andres/dropbox/Apps/CircuitHub/parts/kicad/CircuitHub
LibName32=/home/andres/development/github/skycan-hardware/kicadlib/hirose
LibName33=/home/andres/development/github/skycan-hardware/kicadlib/open-project
LibName34=/home/andres/development/github/skycan-hardware/kicadlib/user-misc
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=skycan-cdhs.net
UseCmpFile=1
PadDrill="    0.000000"
PadDrillOvalY="    0.000000"
PadSizeH="    2.650000"
PadSizeV="    2.400000"
PcbTextSizeV="    1.500000"
PcbTextSizeH="    1.500000"
PcbTextThickness="    0.300000"
ModuleTextSizeV="    0.762000"
ModuleTextSizeH="    0.762000"
ModuleTextSizeThickness="    0.127000"
SolderMaskClearance="    0.200000"
SolderMaskMinWidth="    0.000000"
DrawSegmentWidth="    0.200000"
BoardOutlineThickness="    0.025400"
ModuleOutlineThickness="    0.150000"
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=led
LibName10=dip_sockets
LibName11=/home/andres/dropbox/Apps/CircuitHub/parts/kicad/CircuitHub
LibName12=/home/andres/development/github/skycan-hardware/kicadlib/hirose
LibName13=/home/andres/development/github/skycan-hardware/kicadlib/open-project
LibName14=/home/andres/development/github/skycan-hardware/kicadlib/sk-abracon
LibName15=/home/andres/development/github/skycan-hardware/kicadlib/user-misc
LibName16=/home/andres/development/github/skycan-hardware/kicadlib/skycan-cdhs-logo
LibName17=/home/andres/development/github/skycan-hardware/kicadlib/OSHW-logo
LibName18=/home/andres/development/github/skycan-hardware/kicadlib/skycan-eps-logo
